- hosts: webservers
  become: true
  tasks:
  - name: installation of apache
    apt: 
     name: apache2
     update_cache: yes
     state: present

  - name: checking the status of apache
    service: 
     name: apache2
     state: started