- hosts: webservers
  become: true
  tasks:
  - name: installing nginx software
    apt:
      name: nginx
      state: latest

  - name: start nginx service
    service:
      name: nginx
      state: started